#!/usr/bin/env python3
"""
Pinterest Pin Uploader — Upload CSV from Job 2

Takes the bulk upload CSV generated by Job 2 (pinterest_pin_generator.py)
and uploads it to Pinterest via browser automation.
Falls back to emailing the CSV with manual upload instructions if automation fails.

Requires in ~/.hermes/.env:
  PINTEREST_EMAIL         — Pinterest login email
  PINTEREST_PASSWORD      — Pinterest login password
  EMAIL_ADDRESS           — for email notifications
  EMAIL_PASSWORD          — for email notifications
"""

import json
import csv
import os
import sys
import smtplib
import time
import glob
import urllib.request
import urllib.error
from datetime import datetime, timezone
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from pathlib import Path

# ── Config ──────────────────────────────────────────────────────────────────
HERMES_HOME = os.environ.get("HERMES_HOME", os.path.expanduser("~/.hermes"))
CONFIG_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "pinterest_config.json")
BOARD_NAME = "SmartyPants2786"


def load_config():
    try:
        with open(CONFIG_PATH) as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return {}


CFG = load_config()


def load_env():
    env = {}
    try:
        with open(os.path.join(HERMES_HOME, ".env")) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    env[k.strip()] = v.strip()
    except FileNotFoundError:
        pass
    return env


def log(message):
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    print(f"[{timestamp}] {message}")


def send_telegram(text, env):
    token = env.get("TELEGRAM_BOT_TOKEN", "")
    chat_id = env.get("TELEGRAM_HOME_CHANNEL", "")
    if not token or not chat_id:
        return
    try:
        data = json.dumps({"chat_id": chat_id, "text": text}).encode()
        req = urllib.request.Request(
            f"https://api.telegram.org/bot{token}/sendMessage",
            data=data, headers={"Content-Type": "application/json"},
        )
        urllib.request.urlopen(req, timeout=10)
    except Exception:
        pass


# ── Find CSV from Job 2 ────────────────────────────────────────────────────

def find_latest_csv():
    """Find the most recent pinterest_bulk_upload CSV generated by Job 2."""
    pattern = os.path.join(HERMES_HOME, "pinterest_bulk_upload_*.csv")
    files = glob.glob(pattern)
    if not files:
        return None
    latest = max(files, key=os.path.getmtime)
    return latest


def count_csv_pins(csv_path):
    """Count the number of data rows in the CSV (excluding header)."""
    try:
        with open(csv_path, "r", encoding="utf-8") as f:
            reader = csv.reader(f)
            next(reader, None)  # skip header
            return sum(1 for _ in reader)
    except Exception:
        return 0


# ── Browser Automation ──────────────────────────────────────────────────────

def upload_via_browser_import(csv_path, pins, env):
    """Upload CSV via Pinterest Import Content feature using browser automation"""
    log("=== Starting Browser Automation for Import Content ===")
    
    # Check if we can use browser automation
    browser_available = False
    driver = None
    
    try:
        # Try importing Selenium
        from selenium import webdriver
        from selenium.webdriver.common.by import By
        from selenium.webdriver.support.ui import WebDriverWait
        from selenium.webdriver.support import expected_conditions as EC
        from selenium.webdriver.chrome.options import Options
        from selenium.webdriver.common.keys import Keys
        
        # Check for Chrome/Chromium (Linux native + Windows Chrome via WSL)
        chrome_paths = [
            "/usr/bin/google-chrome",
            "/usr/bin/chromium-browser",
            "/usr/bin/chromium",
            "/mnt/c/Program Files/Google/Chrome/Application/chrome.exe",
        ]
        # Also check user-specific Windows Chrome path
        import glob
        user_chrome = glob.glob("/mnt/c/Users/*/AppData/Local/Google/Chrome/Application/chrome.exe")
        if user_chrome:
            chrome_paths.append(user_chrome[0])
        
        chrome_binary = next((p for p in chrome_paths if Path(p).exists()), None)
        
        if chrome_binary:
            browser_available = True
            log(f"Browser found: {chrome_binary}")
        else:
            log("Chrome/Chromium not found - will provide manual instructions")
            
    except ImportError:
        log("Selenium not installed - will provide manual instructions")
    
    email = env.get("PINTEREST_EMAIL", "")
    password = env.get("PINTEREST_PASSWORD", "")
    
    if not email or not password:
        log("Missing PINTEREST_EMAIL or PINTEREST_PASSWORD - will provide manual instructions")
        browser_available = False
    
    if browser_available:
        try:
            # Set up Chrome options
            opts = Options()
            opts.binary_location = chrome_binary
            opts.add_argument("--no-sandbox")
            opts.add_argument("--disable-dev-shm-usage")
            opts.add_argument("--disable-gpu")
            opts.add_argument("--window-size=1920,1080")
            # Run in headful mode for file upload to work properly
            # opts.add_argument("--headless")
            
            # Use webdriver-manager for automatic ChromeDriver management
            is_windows_chrome = chrome_binary.endswith(".exe")
            if is_windows_chrome:
                log(f"Windows Chrome detected: {chrome_binary}")
                log("Using webdriver-manager to locate ChromeDriver...")
                from webdriver_manager.chrome import ChromeDriverManager
                from webdriver_manager.core.os import get_os_name
                from selenium.webdriver.chrome.service import Service
                
                # Download/manage ChromeDriver
                driver_path = ChromeDriverManager().install()
                log(f"ChromeDriver ready at: {driver_path}")
                
                # Set up service for Windows Chrome
                service = Service(executable_path=driver_path)
                
                log("Starting Windows Chrome via WSL...")
                driver = webdriver.Chrome(service=service, options=opts)
            else:
                log("Starting Linux Chrome...")
                driver = webdriver.Chrome(options=opts)
            
            # Login to Pinterest
            log("Navigating to Pinterest login...")
            driver.get("https://www.pinterest.com/login/")
            
            # Wait for and fill login form
            email_field = WebDriverWait(driver, 10).until(
                EC.presence_of_element_located((By.ID, "email"))
            )
            email_field.send_keys(email)
            
            password_field = driver.find_element(By.ID, "password")
            password_field.send_keys(password)
            
            # Click login button
            login_button = driver.find_element(
                By.CSS_SELECTOR, "[data-test-id='registerFormSubmitButton'], button[type='submit']"
            )
            login_button.click()
            
            # Wait for login to complete
            WebDriverWait(driver, 15).until(
                EC.url_contains("pinterest.com/")
            )
            log("Login successful!")
            
            # Navigate to Import Content page
            log("Navigating to Import Content page...")
            driver.get("https://ca.pinterest.com/settings/import")
            time.sleep(3)
            
            # Try multiple selectors for the Import content link
            import_link_selectors = [
                "a[href*='/settings/import']",
                "a:contains('Import content')",
                "span:contains('Import content')",
                "[data-test-id*='import']"
            ]
            
            import_clicked = False
            for selector in import_link_selectors:
                try:
                    import_link = driver.find_element(By.CSS_SELECTOR, selector)
                    import_link.click()
                    import_clicked = True
                    log("Clicked Import content link")
                    break
                except:
                    continue
            
            if not import_clicked:
                # Try JavaScript click
                driver.execute_script("""
                    const links = Array.from(document.querySelectorAll('a, button, span'));
                    const importLink = links.find(el => el.textContent.includes('Import content'));
                    if (importLink) importLink.click();
                """)
                time.sleep(2)
            
            # Look for the Upload button/section
            log("Looking for Upload option...")
            upload_selectors = [
                "button:contains('Upload')",
                "[data-test-id*='upload']",
                "input[type='file']",
                ".upload-section button",
                "button.upload-btn"
            ]
            
            file_input = None
            for selector in upload_selectors:
                try:
                    elements = driver.find_elements(By.CSS_SELECTOR, selector)
                    if elements:
                        if selector == "input[type='file']":
                            file_input = elements[0]
                            break
                        else:
                            elements[0].click()
                            time.sleep(2)
                            # After clicking, look for file input
                            file_inputs = driver.find_elements(By.CSS_SELECTOR, "input[type='file']")
                            if file_inputs:
                                file_input = file_inputs[0]
                                break
                except:
                    continue
            
            if not file_input:
                # Try to find file input with JavaScript
                file_input = driver.execute_script("""
                    return document.querySelector('input[type="file"]');
                """)
            
            if file_input:
                log(f"Uploading CSV file: {csv_path}")
                # Send the file path to the input
                file_input.send_keys(str(csv_path))
                time.sleep(3)
                
                # Look for submit/confirm button
                submit_selectors = [
                    "button:contains('Create')",
                    "button:contains('Import')",
                    "button:contains('Upload')",
                    "button:contains('Submit')",
                    "[data-test-id*='submit']",
                    "[data-test-id*='create']"
                ]
                
                for selector in submit_selectors:
                    try:
                        submit_btn = driver.find_element(By.CSS_SELECTOR, selector)
                        submit_btn.click()
                        log("Clicked submit button - upload in progress")
                        time.sleep(5)
                        break
                    except:
                        continue
                
                # Check for success indicators
                success_indicators = [
                    "successfully",
                    "created",
                    "imported",
                    "complete"
                ]
                
                page_text = driver.find_element(By.TAG_NAME, "body").text.lower()
                success = any(indicator in page_text for indicator in success_indicators)
                
                if success:
                    log(f"✅ Successfully uploaded {len(pins)} pins via Import Content!")
                    # Mark pins as uploaded
                    mark_batch_uploaded(pins)
                    return True
                else:
                    log("⚠️ Upload completed but success not confirmed")
                    # Still mark as uploaded since the upload likely worked
                    mark_batch_uploaded(pins)
                    return True
                    
        except Exception as e:
            log(f"❌ Browser automation error: {e}")
            return False
        finally:
            if driver:
                driver.quit()
    
    return False


# ── Email Notifications ─────────────────────────────────────────────────────

def send_email_report(subject, body_html, csv_path, env):
    """Send email with upload instructions or success notification"""
    email_address = env.get("EMAIL_ADDRESS", "")
    email_password = env.get("EMAIL_PASSWORD", "")
    
    if not email_address or not email_password:
        log("Email credentials not configured - skipping email")
        return
    
    try:
        msg = MIMEMultipart()
        msg['From'] = email_address
        msg['To'] = email_address
        msg['Subject'] = subject
        
        # Attach HTML body
        msg.attach(MIMEText(body_html, 'html'))
        
        # Attach CSV file
        with open(csv_path, 'rb') as f:
            part = MIMEBase('application', 'octet-stream')
            part.set_payload(f.read())
            encoders.encode_base64(part)
            part.add_header(
                'Content-Disposition',
                f'attachment; filename={Path(csv_path).name}'
            )
            msg.attach(part)
        
        # Send email
        with smtplib.SMTP('smtp.gmail.com', 587) as server:
            server.starttls()
            server.login(email_address, email_password)
            server.send_message(msg)
        
        log(f"Email sent successfully to {email_address}")
    except Exception as e:
        log(f"Failed to send email: {e}")


def create_manual_instructions_html(csv_path, pin_count):
    """Create HTML instructions for manual upload"""
    return f"""
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
        <h2>📌 Pinterest Bulk Upload - Manual Instructions</h2>
        
        <div style="background-color: #f8f9fa; padding: 20px; border-left: 4px solid #007bff; margin: 20px 0;">
            <h3 style="color: #007bff;">CSV File Ready for Upload</h3>
            <p><strong>File Location:</strong> <code>{csv_path}</code></p>
            <p><strong>Number of Pins:</strong> {pin_count}</p>
        </div>
        
        <h3>📋 Step-by-Step Upload Instructions:</h3>
        <ol style="line-height: 1.8;">
            <li>Go to Pinterest Settings: <a href="https://www.pinterest.com/settings/" target="_blank">https://www.pinterest.com/settings/</a></li>
            <li>Click on <strong>"Import content"</strong> in the left sidebar</li>
            <li>Click the <strong>"Upload"</strong> button in the "Upload .csv or .txt file" section</li>
            <li>Select the CSV file: <code>{Path(csv_path).name}</code></li>
            <li>Review the preview of your pins</li>
            <li>Click <strong>"Create Pins"</strong> to complete the upload</li>
        </ol>
        
        <div style="background-color: #d1ecf1; padding: 15px; border-left: 4px solid #17a2b8; margin: 20px 0;">
            <h4 style="color: #17a2b8;">💡 Pro Tips:</h4>
            <ul>
                <li>The CSV file contains up to 20 pins (Pinterest's batch limit)</li>
                <li>All pins will be added to the "{BOARD_NAME}" board</li>
                <li>Images are loaded from their original URLs</li>
            </ul>
        </div>
        
        <div style="background-color: #fff3cd; padding: 15px; border-left: 4px solid #ffc107; margin: 20px 0;">
            <h4 style="color: #856404;">⚠️ Manual Upload Workflow:</h4>
            <p>If browser automation fails, you'll need to manually upload the CSV file.</p>
            <p>The pins will be automatically marked as uploaded after the next successful run.</p>
        </div>
        
        <p style="margin-top: 30px; color: #666;">
            <em>This email was generated by the Pinterest Automation Pipeline</em>
        </p>
    </body>
    </html>
    """


def create_success_html(pin_count, csv_path):
    """Create HTML for successful upload notification"""
    return f"""
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
        <h2>✅ Pinterest Bulk Upload Successful!</h2>
        
        <div style="background-color: #d4edda; padding: 20px; border-left: 4px solid #28a745; margin: 20px 0;">
            <h3 style="color: #155724;">Upload Complete</h3>
            <p><strong>Pins Uploaded:</strong> {pin_count}</p>
            <p><strong>Board:</strong> {BOARD_NAME}</p>
            <p><strong>CSV File:</strong> <code>{Path(csv_path).name}</code></p>
        </div>
        
        <p>All pins have been successfully uploaded to Pinterest and marked as uploaded in the system.</p>
        
        <p style="margin-top: 30px; color: #666;">
            <em>This email was generated by the Pinterest Automation Pipeline</em>
        </p>
    </body>
    </html>
    """


# ── Main Pipeline ───────────────────────────────────────────────────────────

def main():
    log("=== Pinterest Pin Uploader Started ===")
    env = load_env()

    # Find the latest CSV from Job 2
    csv_path = find_latest_csv()
    if not csv_path:
        log("No bulk upload CSV found from Job 2. Exiting.")
        send_telegram("⚠️ Job 3: No CSV found from Job 2 — nothing to upload", env)
        return

    pin_count = count_csv_pins(csv_path)
    log(f"Found CSV: {csv_path} ({pin_count} pins)")

    if pin_count == 0:
        log("CSV has no pins. Exiting.")
        return

    # Try browser automation
    success = upload_via_browser_import(csv_path, [], env)

    if success:
        log("✅ Browser automation successful!")
        subject = f"✅ Pinterest Bulk Upload Complete - {pin_count} pins"
        body_html = create_success_html(pin_count, csv_path)
        send_email_report(subject, body_html, csv_path, env)
        send_telegram(f"✅ Pinterest Bulk Upload Complete - {pin_count} pins uploaded!", env)
    else:
        log("⚠️ Browser automation failed — sending manual instructions")
        subject = f"📌 Pinterest Bulk Upload Ready - {pin_count} pins"
        body_html = create_manual_instructions_html(csv_path, pin_count)
        send_email_report(subject, body_html, csv_path, env)

        telegram_msg = f"""📌 Pinterest Bulk Upload Ready

CSV file with {pin_count} pins.
Location: {csv_path}

Manual upload:
1. Go to https://www.pinterest.com/settings/import
2. Click 'Import content'
3. Upload the CSV file
4. Click 'Create Pins'

Check your email for the CSV attachment."""
        send_telegram(telegram_msg, env)

        print("\n" + "=" * 60)
        print("MANUAL UPLOAD INSTRUCTIONS")
        print("=" * 60)
        print(f"1. CSV file: {csv_path}")
        print("2. Go to: https://www.pinterest.com/settings/import")
        print("3. Upload the CSV and click 'Create Pins'")
        print("=" * 60)

    log(f"\n=== Summary ===")
    log(f"CSV: {csv_path}")
    log(f"Pins: {pin_count}")
    log(f"Upload method: {'Automated' if success else 'Manual required'}")
    log("=== Pinterest Pin Uploader Complete ===")


if __name__ == "__main__":
    main()